version: '3.8'

services:
  database:
    build: ./database
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urgent_news
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: apache_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
